### ISSUE TITLE
Add ToDo list functionality

### ISSUE THREAD

**Issue by mari1647iv** [mari1647iv/personal-efficiency-helper#3]
Add ToDo functionality according to the MVP and [Figma design mockup](https://www.figma.com/file/0D6TspleL2f30VaCTQGKsS/Personal-Efficiency-Helper?node-id=0%3A1)

- [x] add `todos` database;
- [x] set up ToDo page structure
- [ ] add ToDo list component;
- [ ] sort important todos at the begining;
- [ ] add switch between different ToDo lists;
- [ ] add sort by todos type;
- [ ] add ability to associate timer with current todos.
